# List all the drivers
all: undirectedGraphtest
 
quadtreetest: undirectedGraphtest.cpp
	g++ -std=c++11 -o  undirectedGraphtest undirectedGraphtest.cpp



# List all the executables under 'all:'
clean:
	rm *.o undirectedGraphtest