# List all the drivers
all: quadtreetest
 
quadtreetest: quadtreetest.cpp
	g++ -std=c++11 -o  quadtreetest quadtreetest.cpp



# List all the executables under 'all:'
clean:
	rm *.o quadtreetest